### ISSUE TITLE
[SUGGESTION] : Improve Traditions

### ISSUE THREAD

**Issue by doctorsandwich** [Stellaris-Immortal/retile#117]
Based on discussion in the Discord:
1. Some of the traditions are situational and weak. Domination and Prosperity in particular.
2. Traditions run out + feel forced to invest in ‘bad traditions’
3. Their power level is constant despite increasing research times. For example +5% worker output is pretty bad later in the game.
4. Ascension perk requirements decreasing mean the major restriction is tech, not unity. No reason to invest in unity production
5. Some of the weaker ascension perks become obsolete. Admin cap/edict duration.

Some proposed suggestions:
1. Increase the number of tradition trees, and balance them
2. Empires can only choose 4 tradition trees, but give two ascension perks per tree (beginning and finish)
3. Scale all/most tradition benefits per tradition researched. So 13 traditions -> +13% worker output

**Comment by Metadig** [comment]
A tradition overhaul is in the works. Thanks for the suggestions!
