### ISSUE TITLE
[BUG] : Retrofitting a Federation fleet to your own designs and upgrading it changes ownership to you

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#123]
Retrofitted the Federation Fleet's ship designs to my own designs and ordered an upgrade (as federation president). As a soon as a single ship finishes upgrading it turns "green" when selecting the fleet and looking at the ships, unlike "blue" which federation ships have. The entire fleet then changes ownership from the Federation Fleet to you. It disappears from the Federation Fleet viewer and you pay upkeep and naval capacity for it. I am using Gebnar's branch.

**Comment by gebnar** [comment]
This is normal behavior in vanilla as well. I'm pretty sure it's not something we can fix via modding.
