### ISSUE TITLE
[BUG] : Plantoid/Mechanist Robot Farmers give Food instead of Habitability/Growth

### ISSUE THREAD

**Issue by AstralVoid** [Stellaris-Immortal/retile#126]
Provide a general summary of the issue in the Title above 
Note: If this is a localization error, feel free to submit a pull request with the fixed loc. 

## Expected Behavior
For Robot pops to behave identically to Plantoid pops on farm districts for Plantoid empires starting with the Mechanist civic

## Current Behavior
Plantoid Mechanist empires have robots in the starting farmer slot, which results in food production, rather than habitability/pop growth
Homeworld starts at 80% habitability as a result as well

## Possible Solution
Main possibilities I can think of:
1) Set job priority to favor plantoids over robots for farmer job
2) Add a similar trait to Plantoid-based robots to those empires with plaintoid main species who start with Mechanist (not sure if possible to assign traits to extra species an empire starts with for mechanist/syncretic empires)
3) Modify the district to give a different job than the generic Farmer (Tender?) for Plantoid originated empires (may run into issues where they don't have the ability to support non-plantoid species due to the lack of ability to sustain food/farms)

## Steps to Reproduce
1. Create an empire with materialist/fanatic materialist
2. Choose Mechanist civic
3. Choose Plantoid species
4. Start game

**Comment by gebnar** [comment]
Only plantoids will ever substitute growth for food. This is intentional.
