### ISSUE TITLE
[SUGGESTION] : Federation should satisfy Materialist faction Commercial Pact needs

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#127]
Being in a Federation imposes an automatic Commercial Pact between all of its members, but the Materialist faction requires a Commercial Pact as one of its needs. I propose that being in a Federation is an alternative to a Commercial Pact, in line with how Federations impose it.

**Comment by Metadig** [comment]
This is fixed in for the next update.
