### ISSUE TITLE
[BUG] : AI rebellion spawning too many robot pops: in line with vanilla, not SI

### ISSUE THREAD

**Issue by guto8797** [Stellaris-Immortal/retile#132]
Provide a general summary of the issue in the Title above 
Note: If this is a localization error, feel free to submit a pull request with the fixed loc. 

## Expected Behavior
The AI revolt event occurs when you have sentient AI's with no rights. A chain of events about odd occurrences in your empire plays out, with some options allowing you to delay the revolt, and if you are lucky, make a patch. When the revolt triggers, some planets will randomly be taken over by the AI, which also receives fleets, civilian ships, and machine pops on those planets.

## Current Behavior
The quantity of machine pops spawned has not been adjusted to SI's pop mechanics. In my case, over 500 machine pops spawned in total. Once the planets are reconquered and the revolt put down, all of these pops take a long time to purge, causing instability and crime across all planets.

## Possible Solution
Adjust the event so that the number of machine pops spawned is more in line with SI's systems. Perhaps as a QOL solution it would also be possible to scale the number of pops spawned and the strenght of the rebellion based on the number of robots and how many soldier robots there are.

## Steps to Reproduce
 Provide a save, or a set of steps to 
 reproduce this bug, to the best of your knowledge
1. Research sentient AI, maintain servitude policy
2. Allow AI revolt to occur
3. Retake the planets and observe the massive number of pops.

**Comment by ayyylmaokai** [comment]
The offending event is syndaw.1022.

It triggers this on your capital:

```
while = {
				#limit = { free_housing > 0 }
				count = 10
				create_pop = {
					species = root
				}
			}
			
			if = {
				limit = {
					count_owned_pops = {
						count < 5
						limit = { is_exact_same_species = root }
					}
				}
				while = {
					limit = {
						count_owned_pops = {
							count < 5
							limit = { is_exact_same_species = root }
						}
					}
					random_owned_pop = {
						limit = { NOT = { is_exact_same_species = root } }
						kill_pop = yes
						prev = {
							create_pop = {
								species = root
							}						
						}
					}
				}
			}
```

and this on other random planets

```
while = {
						limit = { free_housing > 0 }
						create_pop = {
							species = root
						}
					}

					if = {
						limit = {
							count_owned_pops = {
								count < 5
								limit = { is_exact_same_species = root }
							}
						}
						while = {
							limit = {
								count_owned_pops = {
									count < 5
									limit = { is_exact_same_species = root }
								}
							}
							random_owned_pop = {
								limit = { NOT = { is_exact_same_species = root } }
								kill_pop = yes
								prev = {
									create_pop = {
										species = root
									}								
								}
							}
						}
					}
```

**Comment by Vstef** [comment]
On the latest Steam update they have normal SI values. A rebellion happened in my game and it has 2 planets with a total of 30 pops combined. There are other issues with rebellions because machine empires haven't been reworked yet.

**Comment by guto8797** [comment]
It probably scales with planet number. I should have mentioned it, but in my case the rebellion seized something like 5 planets

**Comment by ayyylmaokai** [comment]
so you had 500 machine pops over 5 planets? Do you have the save?

**Comment by guto8797** [comment]
Can only get back to it tomorrow, ill see if I have the moment the rebellion went online to see precise numbers

**Comment by Turmfalke2** [comment]
Can confirm. The ai rebellion has 4 planets with 310 pops. The empire they spawned from has 5 planets with 29 pops.

**Comment by guto8797** [comment]
![image](https://user-images.githubusercontent.com/7987524/69503193-4ed92080-0f0f-11ea-9f54-1080fe1a2f51.png)
Managed to go back to the moment of the rebellion. 6 Planets, 415 pops, with 36 pops to convert. Also, many of my pops ended up on the market, but this shouldn't be possible, the market screen says the machines have no access to the galactic market, only if they turned on displacement purging.

**Comment by gebnar** [comment]
This is not an issue with these events disabled. These will be reworked soon, probably after machine empires are fully implemented.
