### ISSUE TITLE
[BUG] : Every building provides custodian jobs instead of what it should be providing

### ISSUE THREAD

**Issue by Gort1** [Stellaris-Immortal/retile#135]
After the update yesterday all my buildings are providing custodian jobs instead of what they're meant to be providing.

This does not affect districts (those still seem to be doing what they should be) but it does affect all buildings.

This bug is easily verified by starting a new game and looking at your starting planet. It should have no custodian jobs and two engineer jobs (one from the city district, one from the alloy foundries) but instead it has one custodian job and one engineer job, since the job from the alloy foundries is a custodian job instead of an engineer job.

**Comment by Vstef** [comment]
I'm not sure I understand what you mean. All buildings provide Custodian jobs. Alloy Foundries and upgrades of it increase the base alloy yield of Engineers and their pollution produced per job. Similarly, this happens with artisan (CG) buildings, research and unity. Engineer and Scholar jobs should only come from City Districts or special planetary features (from events).

**Comment by Metadig** [comment]
Buildings provide the custodians needed to clean up after the jobs they increase the productivity for. This prevents you from having to build too many custodial districts on each planet to manage the pollution.

In short, this is working as intended.
