### ISSUE TITLE
[BUG] : Elections not functioning for Democracies

### ISSUE THREAD

**Issue by guto8797** [Stellaris-Immortal/retile#138]
Elections aren't working as they should.

All that appears is a blank screen with no candidates and no possibility to elect anyone, current leader is re-elected.

![image](https://user-images.githubusercontent.com/7987524/69587067-603c2e80-0fdc-11ea-9eff-b2d4b4e4e5ba.png)

However, Oligarchies are working properly

![image](https://user-images.githubusercontent.com/7987524/69587126-9a0d3500-0fdc-11ea-9039-f3233ea96a74.png)

As are Dictatorships

![image](https://user-images.githubusercontent.com/7987524/69587154-adb89b80-0fdc-11ea-81ae-7c885ee37dff.png)

If the democratic ruler dies, elections begin with no candidates, and after a while the game generates a random ruler that gets elected

**Comment by Metadig** [comment]
This is a far more serious bug than expected. Might be a back end issue. I'm going to revert democracy for now and do something about the mandates at a later time.
