### ISSUE TITLE
Almost everyone has inward perfection

### ISSUE THREAD

**Issue by Pbprovost** [Stellaris-Immortal/retile#140]
Starting several games with random AIs, almost everyone gets inward perfection. It seems it no longer requires anything and all empires can get it, and the odds of it appearing seem very high. Out of 18 empires, 14 of them are inward perfection and 3 are megacorps who can't take it. When we rescued the limbo robots and they made an empire, they also rolled with it.

It's kind of difficult trying to play as a megacorp or a federation builder when 75% of empires are inward focused. In my megacorp game I was only able to make two commercial pacts with the entire galaxy - the only megacorp that wasn't a criminal syndicate and the single normal empire that wasn't inward focused.

I tried rolling a second and a third game and looking at the empires and the results aren't quite as extreme, but are similar. This second game has 10 out of 18 that are inward. The third has 11 out of 18.

While it's a fairly strong perk mechanically, it makes for pretty boring games when everyone just grows and sits there not making any alliances or attacking anyone.

**Comment by Stylether** [comment]
I believe this problem lies in the root of the requirement accidentally being flipped. You can only pick the civic if you're _not_ pacifist, instead of what the tooltip says. Since pacifism isn't extremely prevalent in generated galaxies (usually), flipping this back to what it was supposed to be should fix your problem as well.

**Comment by gebnar** [comment]
This may also have to do with the Civic ai weight. It may have been
weighted extra high due to it being a combination that was rarely viable.

**Comment by Vstef** [comment]
Default vanilla weight is 1000 whereas every other civic is 5. The restrictive ethic requirements kept it from being too prevalent, so now that there's no longer that limitation it will be picked all the time.

**Comment by Metadig** [comment]
This will be fixed in the next update.
