### ISSUE TITLE
[BUG] : Centrists support xenophobia

### ISSUE THREAD

**Issue by doctorsandwich** [Stellaris-Immortal/retile#179]
Centrists in-code are referred to as the ‘supremacist’ faction. That means dated references to the supremacist faction now refer to the centrist faction unintentionally.

## Expected Behavior
 Centrist factions are politically neutral

## Current Behavior
Centrist faction supports xenophobe ethic

## Possible Solution
 Remove all references to ‘supremacist’ in the ethics txt file

## Steps to Reproduce
 Provide a save, or a set of steps to 
 reproduce this bug, to the best of your knowledge
1.
2.
3.
4.

**Comment by Metadig** [comment]
This is realistic, but I'll fix it anyway.

**Comment by Metadig** [comment]
All traces should be removed in the next update.
