### ISSUE TITLE
[SUGGESTION] : Return Fanatic Purifiers to their vanilla ethics

### ISSUE THREAD

**Issue by TaosMonk** [Stellaris-Immortal/retile#188]
Making them all Fanatic Militarists doesn't make much sense, when they are clearly about hating other aliens so much that it hurts them to live in the same universe with them. I'd suggest making them either Fanatic Militarist + Xenophobe, or Fanatic Xenophobe + any other ethic.

**Comment by Metadig** [comment]
That was an error on my part.

In the next update they will be limited to either Fanatic Xenophobe + Militarist OR Fanatic Militarist + Xenophobe.
