### ISSUE TITLE
[Bug]: Empire Cohesion penalty for separated colonies

### ISSUE THREAD

**Issue by draconas1** [Stellaris-Immortal/retile#192]
Not sure if this is an underlying game issue and just never stumbled across it before:  Playing as commonwealth of man, claim my 2nd system and immiedately get a low cohesion warning.  
Seeing the cohesion popup shows i am losing a lot through external hyperlinks (correct) and some from "unconnected systems"
I only have 2 systems at this point in the game, and they are adjacent!

## Expected Behavior
Did not expect unconnected systems penalty.  

## Current Behavior
Small penalty for unconnected systems despite all systems being connected

## Possible Solution
None sorry.  

## Steps to Reproduce
No mods save Immortal + UI Overhaul dynamic.  

I would attach a save game but Github does not allow it.
Shared on google drive here: https://drive.google.com/open?id=1cZqmwt5z6G5nhgDtS8C03RRk_1OXZ95_

**Comment by Vstef** [comment]
Stellaris Immortal has more cohesion loss for external hyperlinks than vanilla. Isolated systems (aka systems that have all hyperlanes surrounded by your empire) have 3 cohesion loss like vanilla. Starbases increase cohesion by 5, vanilla is 3.

**Comment by gebnar** [comment]
Cohesion is removed a while ago in the mod, and now in vanilla.
