### ISSUE TITLE
[BUG] : Numistic shrine unlimited uses

### ISSUE THREAD

**Issue by Feone** [Stellaris-Immortal/retile#217]
The Numistic Shrine decision can be used on every single planet and habitat after receiving it once from the Caravaneers (latest Steam version).

**Comment by Metadig** [comment]
The building in the vanilla code doesn't show a flag or anything that would limit it to only being built once. Are you sure this isn't the default intended behavior?

**Comment by Feone** [comment]
I'm not certain, I've never gotten it on vanilla. if I recall correctly the wording suggested there would be one but could be a bug in the base game or just awkward wording.

**Comment by Stylether** [comment]
Can confirm, the Numistic Shrine does not limit itself to being built only once. Whether this was intended by the dev team I can't say, but it has been this way since it got introduced.

**Comment by gebnar** [comment]
Yeah, as far as I know, this is intentional. There are so many quirky behaviors like this with caravaneers.
