### ISSUE TITLE
Pollution stuck at -100 on all colonies

### ISSUE THREAD

**Issue by jrelmore** [Stellaris-Immortal/retile#230]
Pollution is not being calculated and/or applied to any planets other than homeworlds when I use this mod. I'm not sure what the problem could be. I've attached two pictures. One of the pollution from a representative planet that should have at least ~200 pollution from jobs and another which is the pollution from my homeworld.
<img width="520" alt="Pollution issues - colony 1" src="https://user-images.githubusercontent.com/17393137/71760174-2a595800-2e6e-11ea-860f-4f516a85e8a6.png">
<img width="525" alt="Pollution issues - earth" src="https://user-images.githubusercontent.com/17393137/71760175-2a595800-2e6e-11ea-9ffe-405846c68b8b.png">

**Comment by Feone** [comment]
Are there any planetary deposits, jobs, leader traits or starbase modules that could offset it? The display breaks once it's at -100 but I've not noticed it being wrong on my games.

**Comment by Metadig** [comment]
This is a display only issue that is, sadly, hard coded into the game.
