### ISSUE TITLE
[BUG] : Relic world central spire provides more housing than jobs

### ISSUE THREAD

**Issue by Feone** [Stellaris-Immortal/retile#27]
The central spire on the rubricator relic world provides 4 housing but only 2 jobs, I haven't found any way to correct this with other buildings or options.

![centralspire](https://user-images.githubusercontent.com/8413938/68605443-b4a7c000-04ac-11ea-9625-50c9de8b3645.png)

**Comment by gebnar** [comment]
I'll get right on that!

**Comment by gebnar** [comment]
Thanks for the reminder!

**Comment by gebnar** [comment]
Fixed.
