### ISSUE TITLE
[BUG] : Mechanist civic seems to cause issues

### ISSUE THREAD

**Issue by Kurgis** [Stellaris-Immortal/retile#278]
## Expected Behavior
 One clerk would be replaced with a Roboticist.

## Current Behavior
 Negative clerks, and not enough housing.
![problem](https://user-images.githubusercontent.com/35203040/72963692-e4652500-3d85-11ea-8d5a-ec32389674fe.png)

## Steps to Reproduce
 Provide a save, or a set of steps to 
 reproduce this bug, to the best of your knowledge
1. Select mechanist civic
2. Upgrade a colony to tier 1
3. You are now stuck with 1 extra job, and -1 housing.

**Comment by Metadig** [comment]
Resolved
