### ISSUE TITLE
[SUGGESTION] : Why pollution increasing effects have to be green?

### ISSUE THREAD

**Issue by Aephiex** [Stellaris-Immortal/retile#287]
In Stellaris, all positive effects are ***green `#00ff00`*** while all negative effects are ***red `#ff0000`***. However, this is not the case of ~~Amenities~~ Pollution. It always confuse me that a ***red `#ff0000`*** polution represents a good polution level while a ***green `#00ff00`*** polution represents a bad polution level.

While some of the texts can be replaced and recolored, the modifier tooltips can't be recolored this way. So, I mean, why not a flip? Let's just call it Eco-Balance or something and just make it red if negative and green if positive.

Why a change? Because positive effects should be ***green `#00ff00`*** and negative effects should be ***red `#ff0000`***!

**Comment by Metadig** [comment]
This sadly cannot be fixed on our end.
