### ISSUE TITLE
[BUG] : A bit of everything trade policy

### ISSUE THREAD

**Issue by Feone** [Stellaris-Immortal/retile#29]
The AIs appear to have a trade policy with a bit of everything (viewable in commercial pacts) and the info on trade [here](https://steamcommunity.com/workshop/filedetails/discussion/1891758612/1606022547911109517/) states this: "Trade policies have been reworked. You start the game with an alloys policy, and the option to switch to consumer goods, or a bit of everything."

This policy isn't available ingame at game start:
![TradeAtStart](https://user-images.githubusercontent.com/8413938/68607087-259ca700-04b0-11ea-8b4e-de0deade79ef.PNG)

Or later in game with most non-repeating research completed:

![TradeLater](https://user-images.githubusercontent.com/8413938/68607090-27666a80-04b0-11ea-8394-a1e9a0edc65f.PNG)

**Comment by gebnar** [comment]
The description on the workshop discussion is outdated. And the AI will soon be reworked to not use that policy either.

I'll update the discussion thread. Thanks for pointing this out!
