### ISSUE TITLE
[BUG] : Living Metal cannot be researched if bought at the market

### ISSUE THREAD

**Issue by draconas1** [Stellaris-Immortal/retile#298]
This is actually a core game bug, but is easily fixed in a mod.  
The Living metal technology can never appear in research options.  Also living metal should never appear randomly as a deposit.  When the living metal anomaly is rolled the ensuing event spawns the deposit and adds the tech to your list at 20% researched.   
If you don't trigger that event then you don't get the tech.  (also applies if you have a mod that adds a living metal deposit as a deposit, because it never triggers the anomaly event it never triggers the research)

## Expected Behavior
Living metal should be researchable if you manage to acquire some outside of the event chain or find some on a planet

## Current Behavior
Living metal only researchable if you get it via a planet anomaly.  

## Possible Solution
I will submit a pull request shortly with an annual pulse event that checks if the player has living metal or a living metal deposit.
When the event fires, it adds the research option if the player doesn't have it.

**Comment by gebnar** [comment]
Merged PR for this into Staging. Closed.
