### ISSUE TITLE
[BUG] : 2 network buildings in a starbase

### ISSUE THREAD

**Issue by Strimblaster** [Stellaris-Immortal/retile#308]
So i somehow managed to get 2 networks on a starbase so it stack the buffs.  (50% ship fire rate being the most game breaking one)

## Expected Behavior
 Picking the tradition to change the network should replace it

## Current Behavior
 It's currently adding another network so you have the default one + the improved

## Possible Solution
Usually the network is in the first slot and it works at intended but in this case it wasn't in the first slot. Maybe you coded to replace the first slot? 

## Steps to Reproduce
I'm not quite sure because i didn't realize the bug until a long time later

1. Remove the default network
2. Build it in another slot
3. Take the tradition

Obs: I think it replaces what you have in the first slot even if its not what it should replace

Screenshot:
https://cdn.discordapp.com/attachments/642957972695416843/676837981663002634/unknown.png

**Comment by Metadig** [comment]
Networks now have a 0 alloy cost and a 0 build time so you can easily swap incorrect ones.
