### ISSUE TITLE
[BUG] : Pacifist Empires get Impossible Mandate

### ISSUE THREAD

**Issue by hustonp** [Stellaris-Immortal/retile#314]
Current Behavior: When playing a Pacifist Democracy, some of my potential leaders can have a mandate to set my war policy to Unrestricted Wars.

Expected Behavior: I doubt that it's intentional that mandates can require a civic change. This mandate should probably check that the empire is not pacifist.

Version: staging branch, pulled on Feb 12

**Comment by Metadig** [comment]
Will be fixed.
