### ISSUE TITLE
[BUG] : Great Khan and his 100 pop planets

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#32]
Great Khan's planets have 100 pops each. Pops also lack a planet preference, though I suppose that might be a vanilla bug?

**Comment by gebnar** [comment]
Oh well this is certainly a problem!!! I will investigate. Thank you for the report!

**Comment by gebnar** [comment]
Do you recall if the kahn's planets ended up with precisely 100 pops?

**Comment by gebnar** [comment]
Nevermind, I figured out what caused it, and fixed it.

**Comment by gebnar** [comment]
d718e5f
