### ISSUE TITLE
[BUG] : Jobs that add habitability don't remove the growth penalty for having low habitability

### ISSUE THREAD

**Issue by jammi1** [Stellaris-Immortal/retile#321]
When using farmers to gain habitability as a plantoid empire the hab gained seems to not be affecting the growth penalty that you get from being at low hab. 
This means you can end up with a planet at 100% hab that still has a -50% growth penalty.

Other penalties from having low hab such as happiness and upkeep do get removed properly.

**Comment by jammi1** [comment]
After a little more testing this issue seems to also apply to the Hab added by colonists. May be an issue with jobs that increase habitability?

**Comment by gebnar** [comment]
I believe this issue has been resolved. Please re-open if it continues to occur.
