### ISSUE TITLE
[SUGGESTION] : Enigmatic Engineering with +1 Artifact is now super OP.

### ISSUE THREAD

**Issue by weirfish** [Stellaris-Immortal/retile#322]
It translates to +500 EC/mo, which is ridiculously good. 

Suggest nerfing it to 0.2 or similar, which is still +100 EC/mo, but about the minimum required to get a Precursor Insight on cooldown. Alternatively, nerf/change the Sell to Collectors decision

**Comment by Metadig** [comment]
Yup. It's going to give you a cache of artifacts when you select it instead.

**Comment by weirfish** [comment]
I don't agree with this solution, necessarily. It giving you an income is still a valid and reasonable ascension perk, given the actual Enigmatic Engineering bit isn't really that useful (at least, IMO, it certainly doesn't feel impactful), and access to FE components only happens at the very end of the tech tree. 

The slow trickle income of artifacts lets you 

* guarantee your precursor (after 10 years per artifact)
* guarantee L-Gate access (after 10 years per insight, assuming you have one)
* guarantee precursor secrets (which are very expensive and difficult to get if you don't go wide enough to do enough excavs, which makes tall harder to play)
* fish through Arcane Tech (which you almost certainly do not have enough artifacts to do after doing your secrets, unless you're actually w i d e, and still rate-limited to once per 2 years)
* do Peaceful or Military Applicaions (for which the buffs aren't realistically *that* powerful anyway)
* per the last two points, make the Arcane Deciphering tech not a dead draw.

And, in a push, you could liquidate them to prop up your economy.
