### ISSUE TITLE
[BUG] : New systems and habitats don't get the star type planetary modifiers

### ISSUE THREAD

**Issue by ziyakaz** [Stellaris-Immortal/retile#34]
Systems that are spawned after game start (like the precursor home system) and newly constructed habitats do not get star type planetary modifiers.

**Comment by gebnar** [comment]
They should get the modifier when they're colonized, if they don't already have it.

**Comment by gebnar** [comment]
I'll leave this open, since we can still add the modifier to precursors and habitats when they spawn still.

**Comment by ziyakaz** [comment]
They don't when they're colonized. I created a habitat around Uranus, colonized it, and it never got the star modifier.

**Comment by gebnar** [comment]
Thanks for the update! I'll let Meta know it's not working right yet.

**Comment by Metadig** [comment]
The modifiers will generate over the course of the game in the next update.
