### ISSUE TITLE
[BUG] : Metascience lab effect does not match description

### ISSUE THREAD

**Issue by Yegie** [Stellaris-Immortal/retile#404]
Found on Staging as of commit f5d674ef77c59ed4324c361ec411ca4a8022169e 

**Metascience labs do not provide the bonuses the description implies.**

Also the fact that it uses flat numbers instead of percentages (like most other buildings) makes it feel a little out of place and might potentially make it too powerful since it will now stack multiplicatively with other percentage bonuses instead of additively. However this is a balance/design question and not part of this bug.

Base scholar production: +2.5sci +2.5unity +30polution
Base scholar upkeep: -1.5energy -1.5goods

## Expected Behavior
Based on the current description of the building this would be the expected values for the job:
Base scholar production: +5sci +4.5unity +37.5polution
Base scholar upkeep: -1.5energy -1.5goods

## Current Behavior
Here are the actual values for the job with the building present:
Base scholar production: +5sci +4.5unity +60polution
Base scholar upkeep: -3energy -3goods
Polution and upkeep does not match values in description.

## Possible Solution
Either change values to match desc or change desc to match values. I would also recommend checking all other meta science buildings for a similar issue.

**Comment by gebnar** [comment]
This should not be an issue any more with the new economy.
