### ISSUE TITLE
[BUG] : Enforcer decision adds Soldiers

### ISSUE THREAD

**Issue by spacsea** [Stellaris-Immortal/retile#44]
Provide a general summary of the issue in the Title above 
Note: If this is a localization error, feel free to submit a pull request with the fixed loc. 

## Expected Behavior
THe tooltip says enforcers.

## Current Behavior
The decision instead adds soldiers

## Steps to Reproduce
Was performed on a corporate strong/military light/authoritarian ethics

**Comment by spacsea** [comment]
![soldiersinstead](https://user-images.githubusercontent.com/57673361/68679917-09a50e00-0561-11ea-9ee4-e84e29ef23e8.png)

**Comment by gebnar** [comment]
Check your policies. Military police replaces enforcers with soldiers. Your ethics line up, so it might be default for your empire.

**Comment by spacsea** [comment]
Thank you, not sure how I lower crime in that case when my military faction demands such :)

**Comment by gebnar** [comment]
Oh, soldiers should now reduce crime. If they don't with that policy, that's a major bug.

**Comment by gebnar** [comment]
Closing for now. Please re-open if there's need to continue the discussion about military police policy.
