### ISSUE TITLE
[BUG] : Abandoned Habitat Decisions don't have localisation

### ISSUE THREAD

**Issue by draconas1** [Stellaris-Immortal/retile#450]
Got the abandoned habitat with pre-sapient workers.
When i colonised it, I got a collection of decisions to build farm, mine or generators.  These decisions do not have any localisation text.

Would suggest that the localisation text makes it clear that the decision creates a deposit that you can then pay minerals to turn into a farm/mine etc...

**Comment by draconas1** [comment]
Gah was late at night and I missed that it had created non usable deposits.

**Comment by gebnar** [comment]
I believe these are working and localized correctly now. Please re-open if further issues arise!
