### ISSUE TITLE
[BUG] : You can abandon your homeworld on literally day one.

### ISSUE THREAD

**Issue by weirfish** [Stellaris-Immortal/retile#48]
## Expected Behavior
The homeworld should not be abandonable.

## Current Behavior
The homeworld is abandonable

## Possible Solution
Remove that decision from any world designated as the empire homeworld.

## Steps to Reproduce
1. Start a new game
2. Before unpausing, go into your homeworld's decisions list, and abandon colony.
3. Wait exactly 1 year (360 days).
4. Lose the game.

**Comment by weirfish** [comment]
Since it won't let me edit, and I immediately realised I did a wrong, make the possible solution "Designated as empire capital" rather than homeworld.

**Comment by gebnar** [comment]
This is priceless! I will fix it, but yeah...

**Comment by gebnar** [comment]
Fixed:
is_capital = no
