### ISSUE TITLE
[BUG] : Ships have no weapon slots

### ISSUE THREAD

**Issue by civilzadedkille** [Stellaris-Immortal/retile#492]
All the ships have no weapon slots including the ion cannon.Defense platform does have though.
I only have this mod on.
![no weapon slots](https://user-images.githubusercontent.com/62564706/77349282-72886800-6d43-11ea-959f-74ac45f94ae2.png)
EDIT: added the save file
[No weapon slots.zip](https://github.com/Stellaris-Immortal/retile/files/4371302/No.weapon.slots.zip)

EDIT 2:the above was with the steam version. I tried the github one and it is fixed.

**Comment by gebnar** [comment]
That is very weird, i don't know why that would happen aside from maybe an incomplete download by Steam. but it's fixed now.
