### ISSUE TITLE
[SUGGESTION] : Auto-forge reward from artifacts as decision instead of building

### ISSUE THREAD

**Issue by Feone** [Stellaris-Immortal/retile#50]
I got an autoforge from a (rare?) outcome on the reverse engineer minor artifacts option. 

Since this building only gives flat production without bonusses to other jobs it's not really worth using a building slot.

**Comment by gebnar** [comment]
As of the Fallen Empire rework, the auto-forge is now insanely powerful, but won't be usable just yet. I'll need to re-add the code that makes it enabled from that option.

**Comment by gebnar** [comment]
3fb40d6
This should be fixed now. I updated the building logic to allow these provided you gain the right option from the minor relic thingy...

Please re-open the issue if it doesn't work for you.

Also, please note that the buildings do buff jobs, but aren't totally implemented yet. Their job buffs aren't localized, for starters.
