### ISSUE TITLE
[BUG] : Pollution broken on some planets

### ISSUE THREAD

**Issue by civilzadedkille** [Stellaris-Immortal/retile#500]
![Untitled](https://user-images.githubusercontent.com/62564706/77690199-94842380-6fab-11ea-9f05-1bfae756e678.png)
Pollution stuck at -100 on 4 of my planets and no modifiers other than those seen above.Deleting some of the "Maintenance Zones" districts solves it so it seems to happen if you go lower than -100.

**Comment by gebnar** [comment]
This is a weird limitation of the engine. If the total pollution calculation gives a result less than the minimum possible value, no information is shown.

We've verified this is display only. It continues to calculate, and will rise again if you generate enough pollution.

I'll close this, as it's an engine limitation, not something we can fix in the mod.
