### ISSUE TITLE
[BUG] : 

### ISSUE THREAD

**Issue by civilzadedkille** [Stellaris-Immortal/retile#502]
![Untitled](https://user-images.githubusercontent.com/62564706/77718114-bcdf4280-6fea-11ea-9d43-23dba16b17f1.png)

Faction wants gunboat diplomacy which is only available to machine intelligence.

EDIT:
In `\pop_faction_types\retile_militarist.txt` it reads:

		title = "MILITARIST_GUNBOAT_DIPLOMACY"
		unfulfilled_title = "MILITARIST_NO_GUNBOAT_DIPLOMACY"
		desc = "MILITARIST_GUNBOAT_DIPLOMACY_DESC"

and
`trigger = {
			owner = { has_policy_flag = diplo_stance_belligerent }
		}`
I'm guessing it should be supremacist(?) or the policy should be added to organics to match the localization string.

**Comment by gebnar** [comment]
I've adjusted the localization for that faction demand to better represent the appropriate policy choice that will satisfy them. Should suffice for now at least.
