### ISSUE TITLE
[SUGGESTION] : Getting around the -100 pollution restriction

### ISSUE THREAD

**Issue by civilzadedkille** [Stellaris-Immortal/retile#510]
It gets really annoying after you get more than 10 planets to try and figure out whether that maintenance zone gets you to -1000 or -101 pollution as you have to either start doing the math or replacing zones back and forth to find the best balance.
Since not showing any of the contributions to the pollution when you get below -100 is a engine limitation, I was thinking of ways to work around that. The simplest seems to be adding a planet modifier.

My first problem is that in the localisation I've typed this:

 ```
Pollution_Meter:0 "GOOD §HEffects from $AMENITIES$§!"
 Pollution_Meter_desc:0 "Uh oh §HEffects from $AMENITIES$§!"
```

But only this shows:
![Untitled](https://user-images.githubusercontent.com/62564706/77853304-2c705000-71ec-11ea-8c3a-e373af6ff6cc.png)

None of the values or icons relative to pollution show up.Any ideas?

**Comment by gebnar** [comment]
This is why we haven't fixed the UI. It's literally not possible to display the information we want to display, in a way that isn't stupid. I've probably put over 100 hours into trying to make pollution display nicely. Ultimately both the mechanics and the UI for this system are very poorly coded on the back-end. We've twisted it into something that works well enough, and isn't *too* ugly.

I'm sorry. I know it's frustrating.

I'm going to close this issue for now, as I don't believe it's possible to make it work. If you find a working solution, please re-open it, or start a new one! I'm open to new ideas - but I'm not going to invest any more time trying to bash my forehead against this particular brick wall unless I see an opening...
