### ISSUE TITLE
[SUGGESTION] : Alter Zroni/Baol precursor chains.

### ISSUE THREAD

**Issue by weirfish** [Stellaris-Immortal/retile#53]
Zroni is impossible to ensure you complete if you want to expand. In a Criminal Megacorp game, I own 31 systems, which contain 8 habitable planets, including my homeworld, my 2 guaranteed worlds, and the Rubricator relic world. Those 4 worlds are the only ones I inhabit. 

The zroni quest chain requires uninhabited but habitable worlds in order to spawn its archeological sites. Because I only have 4 available, and you can't have more than one site per planet, I cannot finish the quest chain.

This isn't so bad if you know you need to have a certain number of habitable worlds up front, but that kind of industry knowledge shouldn't be expected of a player, especially for something like a precursor civilisation.

Proposed fix: Allow these precursor site spawns to occur on barren/toxic/etc terrestrial worlds, as well as currently habitable ones. 

Note: Baol seems fine, I've had them complete, but may not be.

**Comment by gebnar** [comment]
Yeah, I'll 100% agree with the proposed fix. It's basically the same idea I instantly came to.

**Comment by Metadig** [comment]
Zroni sites can now appear on barren, cold barren, and toxic worlds in addition to habitable worlds.
