### ISSUE TITLE
[TODO] : Ethic Modifications

### ISSUE THREAD

**Issue by gebnar** [Stellaris-Immortal/retile#61]
Since pop upkeeps are lower now, Spiritualist should probably be -12.5%/-25% pop upkeep.
Not sure Fanatic Diplomat should be restricted to Defensive Wars Only.

**Comment by spacer99** [comment]
There is a fanatic diplomat ethic? Is that a new feature?

**Comment by gebnar** [comment]
Pacifists are gone, diplomats are in.

**Comment by Metadig** [comment]
Spiritualists buffed.
