### ISSUE TITLE
[BUG] : +2/-2 crime effects coming from wrong traits

### ISSUE THREAD

**Issue by Jamba111** [Stellaris-Immortal/retile#64]
The Dirty and Clean traits are giving a +2/-2 crime effect alongside there other effect. Meanwhile Deviant and Conformist have no effect.

**Comment by gebnar** [comment]
Lol. That can't be true for all pop categories, since some were working right. But man it's a hilarious copy-paste error. I'll get to it ASAP.

**Comment by gebnar** [comment]
Ok.. Yeah I screwed this up bad. It was indeed broken everywhere, but I tested with both active like a dummy. It's fixed now. Thank you very much for the report!!!

745f654
