### ISSUE TITLE
[SUGGESTION] : Revisit Agrarian Idyll and Mining Guilds.

### ISSUE THREAD

**Issue by weirfish** [Stellaris-Immortal/retile#67]
Both these civics suffer from the economy rework, even as presented (currently +3 unity from Farmers and Miners respectively). 

You want your food income to only ever be as high as needed to cover your pops requirements, and your mineral income to be as high as needed to cover alloy and supply production. Therefore, building extra mines and farms to properly utilise these civics is a suboptimal strategy, and that makes them something of a noobtrap. 

Proposed solution: Make the appropriate job provide less pollution (after all, it's what the empire is built around), and have Agrarian Idyll give free Supplies and Mining Guilds give free Alloys. Or both supplies maybe. Farms giving alloys would be weird tho.

**Comment by gebnar** [comment]
I think both giving just supplies would be nice, actually. It would mean you might be able to replace some factory buildings with some rural jobs providing your supplies.

That said, I'm gonna put this one at a relatively low priority for now. You can always switch out of the civic if it's bad late-game. Eventually we're going to do a full civic overhaul.

In fact, I think there's already an issue for that, so I'll probably just copy/paste your suggestion there, and close this issue to reduce clutter.
