### ISSUE TITLE
[BUG] : Gospel of the Masses doesn’t give bonus trade value for spiritualist pops

### ISSUE THREAD

**Issue by doctorsandwich** [Stellaris-Immortal/retile#68]
When taking the civic gospel of the masses, spiritualist pops don’t seem to give bonus trade value.

## Expected Behavior
 Each spiritualist pop gives 3 additional trade value

## Current Behavior
Trade value from pops is always small, never above 5-6. Even when @trade_value_prosperity_gospel is edited to something large like 300 nothing changes.

## Steps to Reproduce
Start a new game with gospel of masses, observe trade value from pops over the course of the year, notice how low it is

**Comment by gebnar** [comment]
Thanks for letting us know!

**Comment by gebnar** [comment]
Fixed
a96c671
