### ISSUE TITLE
[BUG] : No upgradable building icon in outliner

### ISSUE THREAD

**Issue by Feone** [Stellaris-Immortal/retile#69]
When a planet has buildings available for upgrading there is no icon in the outliner to let you know. 

![stellarisicon](https://user-images.githubusercontent.com/8413938/68890217-b8427d80-071e-11ea-87d9-77776b0e91c0.PNG)

**Comment by gebnar** [comment]
This is an odd issue. I've had it in vanilla too. I'll see what I can do...

**Comment by gebnar** [comment]
I think I've figured this out. If you have any open building slots, the upgrade icon is not shown in preference of the empty slot icon.

I'm closing this for now. If you find this to not be the only cause, please report and reopen the issue.
