### ISSUE TITLE
[TODO] : make precursors optionally selectable in some way

### ISSUE THREAD

**Issue by gebnar** [Stellaris-Immortal/retile#72]
Would be nice if you could decide going in which precursor you'd get, at least some of the time.

Maybe link them to some origins, or something...

**Comment by Vstef** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1780597499

Compatible with SI.

**Comment by weirfish** [comment]
I think it's reasonable to forego any other origin to get a specific precursor. Choosing a precursor is very powerful, especially the Cybrex for robots and the Zroni with psionics. It should have an opportunity cost.

**Comment by gebnar** [comment]
I like that reasoning. At the same time, we can still give precursor-origins some unique flavor and design to better facilitate roleplay.

Also, for what it's worth, as long as the balance doesn't stray disastrously far, I actually agree with the studio that not all things need to be evenly balanced.

**Comment by weirfish** [comment]
Agreed, not everything needs to be balanced, but the player *should* be presented with meaningful choices that have downsides, and forgoing a ringworld start to choose the Cybrex is a pretty reasonable downside.

**Comment by gebnar** [comment]
Closing for now. The recommended mod is an ideal solution.
