### ISSUE TITLE
[BUG] : Plantoids can't be Serviles, Ingenious or Industrious

### ISSUE THREAD

**Issue by dantelorel** [Stellaris-Immortal/retile#77]
Because Plantoids are a separate species archetype, they can't access some standard species traits. Ingenious and Industrious are Biological/Lithoid-only traits, which I don't believe is intentional. Serviles is also Biological/Lithoid-only, which sadly precludes the use of Plantoids as a Syncretic species.

**Comment by Metadig** [comment]
Ingenious and Industrious are pretty bad in the mod right now and will be reworked at some point.

I added plantoids to the syncretic and hive mind options.
