### ISSUE TITLE
[BUG] : You can construct multiple Bioreactors.

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#79]
Bioreactor is uncapped. I have one built on my planet, can still construct more of them on the same planet. Localization indicates the limit should be one.

**Comment by gebnar** [comment]
Definitely a bug. If only a humorous, non-game-breaking one...

**Comment by Vstef** [comment]
Additionally, they can be constructed on Habitats. I have not tested for Ringworlds and Ecumenopolises yet, but might be the case as well.

**Comment by gebnar** [comment]
patched on current staging branch
