### ISSUE TITLE
[SUGGESTION] : Prevent assimilating pops from joining/creating factions

### ISSUE THREAD

**Issue by doctorsandwich** [Stellaris-Immortal/retile#83]
Assimilating slave pops to become cybernetic allows them to create factions, such as the egalitarian faction.

**Comment by gebnar** [comment]
It probably just reset their species rights. Try setting if they're actually still slaves.

**Comment by doctorsandwich** [comment]
I mean it created the faction while they were assimilating

**Comment by gebnar** [comment]
Oh. Yeah we should be able to fix that.

**Comment by gebnar** [comment]
fixed
