### ISSUE TITLE
[BUG] : Automigration code does not account for built machine pops.

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#89]
Organic pops get migrated instantly if there is no housing as per on_actions, however this does not apply for mechanical pops, perhaps the on_pop_growth in on_actions does not apply to assembly pops. The machine pops will get migrated after a few months as per the code in retile_pop_events, but won't automatically migrate them instantly if there is no housing.

**Comment by gebnar** [comment]
patched in current staging branch
