### ISSUE TITLE
[SUGGESTION] : Federation Naval Capacity

### ISSUE THREAD

**Issue by Vstef** [Stellaris-Immortal/retile#92]
Might be too early to change with the upcoming changes in the next expansion, but I feel like the 500 capacity cap on Federations is wasted on Empires that can provide more. For example, my allies provide the maximum 500 cap, but I still contribute 20% of my capacity that goes nowhere because the max has been reached already.

**Comment by gebnar** [comment]
Yeah this is a good one to put off until Federations hits. Though I may increase the cap in the meantime...

**Comment by Vstef** [comment]
And lower the contribution, I feel like 20% is a bit much, especially with Diplomacy traditions.

**Comment by gebnar** [comment]
How about 1000 cap, with 15% contribution? (Assuming I can make it work?)

**Comment by Vstef** [comment]
That'd be more reasonable, though I'd reduce the contribution even further to 10%. It's buffed to 20% by the entente diplomacy tradition and an AI will typically have about 600 capacity (right now, they don't seem to favor anchorages), so 120 or so from each member can make a good fleet with some room to spare for the player.

**Comment by gebnar** [comment]
Changed in /gebnar, will be pulled to staging
f0830c6

Cap changed to 1000
Contribution reduced to 12%
